server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_schema?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true


rest:
  template:
    read:
      timeout: 10000
    connect:
      timeout: 10000
